# This is a basic workflow to help you get started with Actions

name: Test Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      # Runs a set of commands using the runners shell
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          sudo apt install aria2 mingw-w64 alsa libasound2-dev libpulse-dev cbindgen libdbus-glib2.0-cil-dev libgtk-3-0 libgtk-3-dev libpango-1.0-0 libpango1.0-dev nasm libnss3-dev libnss3
          npm install web-ext -g

      # Runs a set of commands using the runners shell
      - name: Configure and Build
        run: |
          python configurator.py -c test/config.json
          cd build
          python build.py
